# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [0]:
iris = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = df.data
y = df.target

In [0]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state = 0)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow.keras.utils import to_categorical
y_test = to_categorical(y_test,num_classes=3)
y_train = to_categorical(y_train, num_classes=3,)
y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras.models import Sequential

In [0]:
# Initializing the ANN
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
from tensorflow.keras.layers import Dense

In [0]:
# The amount of nodes (dimensions) in hidden layer should be the average of input and output layers.
# This adds the input layer (by specifying input dimension) AND the first hidden layer (units)
model.add(Dense(3, activation = 'sigmoid', input_shape=(4,)))

In [0]:
#Add 1st hidden layer
model.add(Dense(3, activation='sigmoid'))

In [0]:
# Adding the output layer
# Notice that we do not need to specify input dim. 
# we have an output of 3 node, which is the the desired dimensions of our output (stay with the bank or not)
# We use the sigmoid because we want probability outcomes
model.add(Dense(3, activation = 'softmax')) 

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 12        
Total params: 39
Trainable params: 39
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
model.fit(X_train, y_train,           
          validation_data=(X_test,y_test),
          epochs=100,
          batch_size=32)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 2s 14ms/sample - loss: 1.1046 - accuracy: 0.3304 - val_loss: 1.0678 - val_accuracy: 0.3421
Epoch 2/100
112/112 [==============================] - 0s 269us/sample - loss: 1.1036 - accuracy: 0.3304 - val_loss: 1.0679 - val_accuracy: 0.3421
Epoch 3/100
112/112 [==============================] - 0s 240us/sample - loss: 1.1027 - accuracy: 0.3304 - val_loss: 1.0680 - val_accuracy: 0.3421
Epoch 4/100
112/112 [==============================] - 0s 254us/sample - loss: 1.1016 - accuracy: 0.3304 - val_loss: 1.0681 - val_accuracy: 0.3421
Epoch 5/100
112/112 [==============================] - 0s 232us/sample - loss: 1.1010 - accuracy: 0.3304 - val_loss: 1.0681 - val_accuracy: 0.3421
Epoch 6/100
112/112 [==============================] - 0s 227us/sample - loss: 1.1002 - accuracy: 0.3304 - val_loss: 1.0681 - val_accuracy: 0.3421
Epoch 7/100
112/112 [==============================] - 0s 241us/sample - l

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_pred = model.predict(X_test)
print(y_pred[0])

[0.30593687 0.30569553 0.3467099 ]


In [0]:
y_pred = model.predict(np.expand_dims(X_test[0],axis=0))

In [0]:
y_pred

array([[0.30593684, 0.30569553, 0.3467099 ]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
print("Prediction: {}".format(tf.argmax(y_pred[0])))
print("Labels: {}".format(tf.argmax(y_test[0])))

Prediction: 2
Labels: 2


In [0]:
y_test[0]

array([0., 0., 1.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [4]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

{}

In [0]:
import numpy as np
import pandas as pd


In [0]:
stock = pd.read_csv('prices.csv')

In [57]:
stock.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [58]:
stock.drop(['date','symbol'], axis =1,  inplace=True)
stock.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
stock = stock.iloc[0:1000]

In [60]:
stock.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
stock_X = stock.iloc[:,:-1]
stock_Y = stock.iloc[:,-1]

In [0]:
stock_Y = stock_Y/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
features = stock_X
labels = stock_Y

In [64]:
print(features.dtypes)
print(labels.dtypes)

open     float64
close    float64
low      float64
high     float64
dtype: object
float64


In [0]:
labels = np.float32(labels)
features = np.float32(features)

In [66]:
features 

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

In [67]:
labels 

array([2.163600e+00, 2.386400e+00, 2.489500e+00, 2.006300e+00,
       1.408600e+00, 1.098000e+00, 9.496000e-01, 7.853000e-01,
       1.093700e+00, 1.523500e+00, 1.653900e+00, 9.443000e-01,
       7.449000e-01, 7.038000e-01, 5.631000e-01, 8.961000e-01,
       6.804000e-01, 7.499000e-01, 5.742000e-01, 6.948000e-01,
       8.963000e-01, 9.563000e-01, 9.971000e-01, 1.200500e+00,
       1.725200e+00, 1.946000e+00, 1.319500e+00, 9.224000e-01,
       1.185100e+00, 9.215000e-01, 4.409000e-01, 1.244300e+00,
       6.813000e-01, 4.112000e-01, 4.473000e-01, 5.592000e-01,
       4.599000e-01, 9.716000e-01, 6.941000e-01, 1.159600e+00,
       8.847000e-01, 6.920000e-01, 8.980000e-01, 8.445000e-01,
       7.965000e-01, 4.168000e-01, 5.902000e-01, 4.951000e-01,
       5.158000e-01, 5.621000e-01, 8.093000e-01, 1.607300e+00,
       1.001300e+00, 7.114000e-01, 4.442000e-01, 5.341000e-01,
       7.982000e-01, 5.910000e-01, 4.432000e-01, 5.780000e-01,
       7.651000e-01, 5.143000e-01, 1.150000e+00, 2.0353

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
features_norm = tf.math.l2_normalize(features)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [54]:
weight = []
bias=[]
for i in range(100):    
    w, b = train(features_norm, labels, w, b)
    weight.append(w)
    bias.append(b)
    print('Current Loss on iteration', i, loss(labels, prediction(features_norm, w, b)).numpy())

Current Loss on iteration 0 209.52168
Current Loss on iteration 1 209.50285
Current Loss on iteration 2 209.48473
Current Loss on iteration 3 209.46733
Current Loss on iteration 4 209.4506
Current Loss on iteration 5 209.43457
Current Loss on iteration 6 209.41917
Current Loss on iteration 7 209.40437
Current Loss on iteration 8 209.39018
Current Loss on iteration 9 209.37653
Current Loss on iteration 10 209.36342
Current Loss on iteration 11 209.35081
Current Loss on iteration 12 209.33875
Current Loss on iteration 13 209.32712
Current Loss on iteration 14 209.31598
Current Loss on iteration 15 209.30528
Current Loss on iteration 16 209.29498
Current Loss on iteration 17 209.28513
Current Loss on iteration 18 209.27565
Current Loss on iteration 19 209.26654
Current Loss on iteration 20 209.2578
Current Loss on iteration 21 209.24937
Current Loss on iteration 22 209.24133
Current Loss on iteration 23 209.23357
Current Loss on iteration 24 209.22614
Current Loss on iteration 25 209.219


In [34]:
features_norm

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

### Observe values of Weight
- Print the updated values

In [69]:
w

<tf.Tensor: id=27824, shape=(4, 1), dtype=float32, numpy=
array([[0.06199218],
       [0.06210442],
       [0.06136353],
       [0.06261288]], dtype=float32)>

### Observe values of Bias
- Print the updated values

In [70]:
b

<tf.Tensor: id=27827, shape=(1,), dtype=float32, numpy=array([5.2180204], dtype=float32)>