In [1]:
!pip install -U tensorflow==2

     |████████████████████████████████| 86.3MB 52kB/s 
     |████████████████████████████████| 3.8MB 52.6MB/s 
     |████████████████████████████████| 450kB 43.0MB/s 
     |████████████████████████████████| 81kB 13.5MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.2 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstall

In [0]:
import tensorflow as tf

In [2]:
import keras

Using TensorFlow backend.


In [0]:
import h5py 

In [0]:
import numpy as np

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
filename = '/content/drive/My Drive/Colab Notebooks/SVHN_single_grey1-2.h5'
f = h5py.File(filename, 'r')

In [31]:
for key in f.keys():
  print("shape of " + str(key) + " is: " + str(f[key].shape))

shape of X_test is: (18000, 32, 32)
shape of X_train is: (42000, 32, 32)
shape of X_val is: (60000, 32, 32)
shape of y_test is: (18000,)
shape of y_train is: (42000,)
shape of y_val is: (60000,)


In [32]:
f['y_test'][0]

1

In [33]:
f['y_val'][0]

0

In [34]:
f['X_train'][0]

array([[ 33.0704,  30.2601,  26.852 , ...,  71.4471,  58.2204,  42.9939],
       [ 25.2283,  25.5533,  29.9765, ..., 113.0209, 103.3639,  84.2949],
       [ 26.2775,  22.6137,  40.4763, ..., 113.3028, 121.775 , 115.4228],
       ...,
       [ 28.5502,  36.212 ,  45.0801, ...,  24.1359,  25.0927,  26.0603],
       [ 38.4352,  26.4733,  23.2717, ...,  28.1094,  29.4683,  30.0661],
       [ 50.2984,  26.0773,  24.0389, ...,  49.6682,  50.853 ,  53.0377]],
      dtype=float32)

In [35]:
np.unique(f['y_test'])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [36]:
np.unique(f['y_train'])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [37]:
np.unique(f['y_val'])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [0]:
trainY = tf.keras.utils.to_categorical(f['y_train'],num_classes=10)

In [0]:
testY = tf.keras.utils.to_categorical(f['y_test'], num_classes=10)

In [0]:
valY = tf.keras.utils.to_categorical(f['y_val'], num_classes=10)

In [41]:
trainY

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
# clear out tensorflow memory
tf.keras.backend.clear_session()

In [0]:
model = tf.keras.models.Sequential()

In [0]:
#Reshape data from 2D to 1D -> 32x32 to 1024
model.add(tf.keras.layers.Reshape((1024,), input_shape=(32,32,)))

In [0]:
#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

In [0]:
# Adding 1st layer
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [0]:
# Adding 2nd layer
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [0]:
# Adding 3rd layer
model.add(tf.keras.layers.Dense(50, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [0]:
# Adding Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
# model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
# using adam as optimizer getting better accuracy

In [52]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 1024)              0         
_________________________________________________________________
batch_normalization (BatchNo (None, 1024)              4096      
_________________________________________________________________
dense (Dense)                (None, 200)               205000    
_________________________________________________________________
batch_normalization_1 (Batch (None, 200)               800       
_________________________________________________________________
dense_1 (Dense)              (None, 100)               20100     
_________________________________________________________________
batch_normalization_2 (Batch (None, 100)               400       
_________________________________________________________________
dense_2 (Dense)              (None, 50)                5

In [53]:
#Train the model
model.fit(f['X_train'][:],trainY,
          validation_data=(f['X_val'][:],valY),
          epochs=15,
          batch_size=32)
# model.fit(f['X_train'][:],trainY,
#           validation_data=(f['X_test'][:],testY),
#           epochs=10,
#           batch_size=32)

Train on 42000 samples, validate on 60000 samples
Epoch 1/15
42000/42000 [==============================] - 12s 295us/sample - loss: 1.4950 - accuracy: 0.5070 - val_loss: 1.0490 - val_accuracy: 0.6696
Epoch 2/15
42000/42000 [==============================] - 11s 267us/sample - loss: 1.0751 - accuracy: 0.6563 - val_loss: 0.7968 - val_accuracy: 0.7553
Epoch 3/15
42000/42000 [==============================] - 11s 268us/sample - loss: 0.9363 - accuracy: 0.7045 - val_loss: 0.7319 - val_accuracy: 0.7758
Epoch 4/15
42000/42000 [==============================] - 11s 265us/sample - loss: 0.8621 - accuracy: 0.7279 - val_loss: 0.6430 - val_accuracy: 0.8035
Epoch 5/15
42000/42000 [==============================] - 11s 270us/sample - loss: 0.8059 - accuracy: 0.7466 - val_loss: 0.6021 - val_accuracy: 0.8185
Epoch 6/15
42000/42000 [==============================] - 11s 259us/sample - loss: 0.7642 - accuracy: 0.7596 - val_loss: 0.5795 - val_accuracy: 0.8245
Epoch 7/15
42000/42000 [====================

In [0]:
predictions = model.predict(f['X_test'][:])

In [55]:
print(predictions[10])
print(np.argmax(predictions[10]))
print(f['y_test'][10])

[1.1043069e-01 1.7107263e-02 1.8490175e-02 1.8913370e-02 3.5971038e-03
 3.2124721e-02 1.3483882e-01 4.9934053e-04 5.2532077e-01 1.3867770e-01]
8
8


In [56]:
print(predictions[900])
print(np.argmax(predictions[900]))
print(f['y_test'][900])

[9.9831164e-01 4.5443339e-05 1.0553692e-05 7.5281372e-05 4.1076778e-06
 1.8254823e-05 1.9709580e-05 7.7558696e-05 2.4516199e-05 1.4128793e-03]
0
0
