In [88]:
import numpy as np
import pandas as pd

In [89]:
#Loading dataframe
df = pd.read_csv('blogtext.csv')

In [90]:
df.head()

id gender  age              topic      sign          date  \
0  2059027   male   15            Student       Leo   14,May,2004   
1  2059027   male   15            Student       Leo   13,May,2004   
2  2059027   male   15            Student       Leo   12,May,2004   
3  2059027   male   15            Student       Leo   12,May,2004   
4  3581210   male   33  InvestmentBanking  Aquarius  11,June,2004   

                                                text  
0             Info has been found (+/- 100 pages,...  
1             These are the team members:   Drewe...  
2             In het kader van kernfusie op aarde...  
3                   testing!!!  testing!!!            
4               Thanks to Yahoo!'s Toolbar I can ...

In [91]:
df.describe()

id            age
count  6.812840e+05  681284.000000
mean   2.397802e+06      23.932326
std    1.247723e+06       7.786009
min    5.114000e+03      13.000000
25%    1.239610e+06      17.000000
50%    2.607577e+06      24.000000
75%    3.525660e+06      26.000000
max    4.337650e+06      48.000000

In [92]:
df.dtypes

id         int64
gender    object
age        int64
topic     object
sign      object
date      object
text      object
dtype: object

In [93]:
df.shape

(681284, 7)

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681284 entries, 0 to 681283
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   id      681284 non-null  int64 
 1   gender  681284 non-null  object
 2   age     681284 non-null  int64 
 3   topic   681284 non-null  object
 4   sign    681284 non-null  object
 5   date    681284 non-null  object
 6   text    681284 non-null  object
dtypes: int64(2), object(5)
memory usage: 36.4+ MB


In [95]:
df['age']=df['age'].astype('object')

In [96]:
df = df.head(10000)

In [97]:
df.shape

(10000, 7)

In [98]:
import re

In [99]:
 def preprocess(sentence):
        sentence = re.sub(r'[^A-Za-z]+',' ',sentence)
        sentence = sentence.lower()
        sentence = sentence.replace(r"\s\s+",' ')
        sentance = sentence.strip()
        sentence = sentence.replace('urllink',"")
        return sentence
df['clean_text'] = df['text'].map(lambda x: preprocess(x))
df.head(10)

id gender age              topic      sign          date  \
0  2059027   male  15            Student       Leo   14,May,2004   
1  2059027   male  15            Student       Leo   13,May,2004   
2  2059027   male  15            Student       Leo   12,May,2004   
3  2059027   male  15            Student       Leo   12,May,2004   
4  3581210   male  33  InvestmentBanking  Aquarius  11,June,2004   
5  3581210   male  33  InvestmentBanking  Aquarius  10,June,2004   
6  3581210   male  33  InvestmentBanking  Aquarius  10,June,2004   
7  3581210   male  33  InvestmentBanking  Aquarius  10,June,2004   
8  3581210   male  33  InvestmentBanking  Aquarius  10,June,2004   
9  3581210   male  33  InvestmentBanking  Aquarius  09,June,2004   

                                                text  \
0             Info has been found (+/- 100 pages,...   
1             These are the team members:   Drewe...   
2             In het kader van kernfusie op aarde...   
3                   testing!!!  testing!!!             
4               Thanks to Yahoo!'s Toolbar I can ...   
5               I had an interesting conversation...   
6               Somehow Coca-Cola has a way of su...   
7               If anything, Korea is a country o...   
8               Take a read of this news article ...   
9               I surf the English news sites a l...   

                                          clean_text  
0   info has been found pages and mb of pdf files...  
1   these are the team members drewes van der laa...  
2   in het kader van kernfusie op aarde maak je e...  
3                                   testing testing   
4   thanks to yahoo s toolbar i can now capture t...  
5   i had an interesting conversation with my dad...  
6   somehow coca cola has a way of summing up thi...  
7   if anything korea is a country of extremes ev...  
8   take a read of this news article from  joonga...  
9   i surf the english news sites a lot looking f...

In [100]:
print("Cleaned data=======> {}".format(df['clean_text'][1]))

Cleaned data=======>  these are the team members drewes van der laag  mail ruiyu xie  mail bryan aaldering me  mail 


In [101]:
import nltk
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [102]:
type (stopwords)

set

In [103]:
df['clean_text'] = df['clean_text'].apply(lambda x: ' '.join([words for words in x.split() if words not in stopwords]))

In [104]:
df.head()

id gender age              topic      sign          date  \
0  2059027   male  15            Student       Leo   14,May,2004   
1  2059027   male  15            Student       Leo   13,May,2004   
2  2059027   male  15            Student       Leo   12,May,2004   
3  2059027   male  15            Student       Leo   12,May,2004   
4  3581210   male  33  InvestmentBanking  Aquarius  11,June,2004   

                                                text  \
0             Info has been found (+/- 100 pages,...   
1             These are the team members:   Drewe...   
2             In het kader van kernfusie op aarde...   
3                   testing!!!  testing!!!             
4               Thanks to Yahoo!'s Toolbar I can ...   

                                          clean_text  
0  info found pages mb pdf files wait untill team...  
1  team members drewes van der laag mail ruiyu xi...  
2  het kader van kernfusie op aarde maak je eigen...  
3                                    testing testing  
4  thanks yahoo toolbar capture urls popups means...

In [105]:
df_copy = df

In [106]:
df['labels'] = df.apply(lambda col: [col['gender'],str(col['age']),col['topic'], col['sign']], axis = 1)
df.head()

id gender age              topic      sign          date  \
0  2059027   male  15            Student       Leo   14,May,2004   
1  2059027   male  15            Student       Leo   13,May,2004   
2  2059027   male  15            Student       Leo   12,May,2004   
3  2059027   male  15            Student       Leo   12,May,2004   
4  3581210   male  33  InvestmentBanking  Aquarius  11,June,2004   

                                                text  \
0             Info has been found (+/- 100 pages,...   
1             These are the team members:   Drewe...   
2             In het kader van kernfusie op aarde...   
3                   testing!!!  testing!!!             
4               Thanks to Yahoo!'s Toolbar I can ...   

                                          clean_text  \
0  info found pages mb pdf files wait untill team...   
1  team members drewes van der laag mail ruiyu xi...   
2  het kader van kernfusie op aarde maak je eigen...   
3                                    testing testing   
4  thanks yahoo toolbar capture urls popups means...   

                                    labels  
0                 [male, 15, Student, Leo]  
1                 [male, 15, Student, Leo]  
2                 [male, 15, Student, Leo]  
3                 [male, 15, Student, Leo]  
4  [male, 33, InvestmentBanking, Aquarius]

In [107]:
df = df[['clean_text','labels']]

In [108]:
df.head()

clean_text  \
0  info found pages mb pdf files wait untill team...   
1  team members drewes van der laag mail ruiyu xi...   
2  het kader van kernfusie op aarde maak je eigen...   
3                                    testing testing   
4  thanks yahoo toolbar capture urls popups means...   

                                    labels  
0                 [male, 15, Student, Leo]  
1                 [male, 15, Student, Leo]  
2                 [male, 15, Student, Leo]  
3                 [male, 15, Student, Leo]  
4  [male, 33, InvestmentBanking, Aquarius]

In [109]:
X = df['clean_text']
Y = df['labels']

In [110]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2)

In [111]:
from sklearn.feature_extraction.text import CountVectorizer

In [112]:
vectorizer=CountVectorizer(binary=True, ngram_range=(1,2))
Xtrain_countVec = vectorizer.fit_transform(Xtrain)
Xtest_countVec = vectorizer.transform(Xtest)

In [113]:
Xtrain_countVec[1]

<1x529675 sparse matrix of type '<class 'numpy.int64'>'
	with 85 stored elements in Compressed Sparse Row format>

In [114]:
Xtest_countVec[1]

<1x529675 sparse matrix of type '<class 'numpy.int64'>'
	with 76 stored elements in Compressed Sparse Row format>

In [115]:
label_counts=dict()

for labels in Y.values:
    for label in labels:
        if label in label_counts:
            label_counts[label]+=1
        else:
            label_counts[label]=1

In [116]:
label_counts

{'male': 5916,
 '15': 602,
 'Student': 1137,
 'Leo': 301,
 '33': 136,
 'InvestmentBanking': 70,
 'Aquarius': 571,
 'female': 4084,
 '14': 212,
 'indUnk': 3287,
 'Aries': 4198,
 '25': 386,
 'Capricorn': 215,
 '17': 1185,
 'Gemini': 150,
 '23': 253,
 'Non-Profit': 71,
 'Cancer': 504,
 'Banking': 16,
 '37': 33,
 'Sagittarius': 1097,
 '26': 234,
 '24': 655,
 'Scorpio': 971,
 '27': 1054,
 'Education': 270,
 '45': 16,
 'Engineering': 127,
 'Libra': 491,
 'Science': 63,
 '34': 553,
 '41': 20,
 'Communications-Media': 99,
 'BusinessServices': 91,
 'Sports-Recreation': 80,
 'Virgo': 236,
 'Taurus': 812,
 'Arts': 45,
 'Pisces': 454,
 '44': 3,
 '16': 440,
 'Internet': 118,
 'Museums-Libraries': 17,
 'Accounting': 4,
 '39': 79,
 '35': 2315,
 'Technology': 2654,
 '36': 1708,
 'Law': 11,
 '46': 7,
 'Consulting': 21,
 'Automotive': 14,
 '42': 14,
 'Religion': 9,
 '13': 42,
 'Fashion': 1622,
 '38': 46,
 '43': 6,
 'Publishing': 4,
 '40': 1,
 'Marketing': 156,
 'LawEnforcement-Security': 10,
 'HumanReso

In [117]:
from sklearn.preprocessing import MultiLabelBinarizer
binarizer=MultiLabelBinarizer(classes=sorted(label_counts.keys()))

In [118]:
df.dtypes

clean_text    object
labels        object
dtype: object

In [119]:
Ytrain=binarizer.fit_transform(Ytrain)
Ytest = binarizer.transform(Ytest)

In [120]:
Y

0                      [male, 15, Student, Leo]
1                      [male, 15, Student, Leo]
2                      [male, 15, Student, Leo]
3                      [male, 15, Student, Leo]
4       [male, 33, InvestmentBanking, Aquarius]
                         ...                   
9995               [female, 25, indUnk, Pisces]
9996               [female, 25, indUnk, Pisces]
9997               [female, 25, indUnk, Pisces]
9998               [female, 25, indUnk, Pisces]
9999               [female, 25, indUnk, Pisces]
Name: labels, Length: 10000, dtype: object

In [121]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='lbfgs')
ovr = OneVsRestClassifier(clf)

In [122]:
ovr.fit(Xtrain_countVec,Ytrain)

OneVsRestClassifier(estimator=LogisticRegression())

In [123]:
y_pred = ovr.predict(Xtest_countVec)

In [124]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [125]:
print('Accuracy',accuracy_score(Ytest,y_pred))
# print('Precision',precision_score(Ytest,y_pred))
print('Precision Weighted',precision_score(Ytest,y_pred,average='weighted'))
print('Recall Weighted',recall_score(Ytest,y_pred,average='weighted'))
# print('Recall',recall_score(Ytest,y_pred))
print('f1 score',f1_score(Ytest,y_pred,average='weighted'))

Accuracy 0.286
Precision Weighted 0.796501373947945
Recall Weighted 0.506125
f1 score 0.5656726229320322


C:\Users\Prakhar\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Prakhar\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Prakhar\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1465: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


In [126]:
print(Ytest)

[[0 0 0 ... 0 1 1]
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [127]:
print(y_pred)

[[0 0 0 ... 0 1 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [128]:
Ytest_inverse = binarizer.inverse_transform(Ytest)
y_pred_inverse = binarizer.inverse_transform(y_pred)

In [129]:
print(Ytest_inverse[0:5],y_pred_inverse[0:5])

[('16', 'Cancer', 'indUnk', 'male'), ('14', 'Cancer', 'Student', 'male'), ('27', 'Aquarius', 'Marketing', 'female'), ('36', 'Aries', 'Fashion', 'male'), ('34', 'Sagittarius', 'female', 'indUnk')] [('indUnk', 'male'), ('female', 'indUnk'), ('27', 'male'), ('Aries', 'male'), ('34', 'Sagittarius', 'female', 'indUnk')]
